name: CI/CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
          cache-version: 1

      - name: Install Yarn conditionally
        run: |
          if ! command -v yarn &> /dev/null; then
            npm install -g yarn
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
          cache-dependency-path: yarn.lock
          cache: "yarn"

      - name: Install Yarn dependencies
        run: |
          yarn install --immutable

      - name: Build assets
        run: |
          bundle exec rails assets:precompile

      - name: Run tests
        run: |
          bundle exec rspec

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
